version: "3"
services:
    pwn:
        build: .
        ports:
            - 5050:5000 #flask / other web
            - 4141:4141 #possibly for future use
        volumes:
            - type: bind
              source: ./shared
              target: /shared
        hostname: new-bark-town
        privileged: true